/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request an OTP code (passwordless auth, 11_API_CONTRACTS.md §11.4) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description email or phone */
                        identifier: string;
                    };
                };
            };
            responses: {
                /** @description OTP sent */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify OTP and receive tokens */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        identifier: string;
                        code: string;
                    };
                };
            };
            responses: {
                /** @description Authenticated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthTokens"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in (or silently register) with a verified Google ID token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description ID token from Google Identity Services' Sign in with Google button */
                        idToken: string;
                    };
                };
            };
            responses: {
                /** @description Authenticated */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthTokens"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Unauthorized"];
                /** @description Google sign-in is not configured on this environment */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/facebook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in (or silently register) with a verified Facebook access token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description User access token from Facebook's JS SDK after FB.login() */
                        accessToken: string;
                    };
                };
            };
            responses: {
                /** @description Authenticated */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthTokens"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Unauthorized"];
                /** @description Facebook sign-in is not configured on this environment */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate access token using a refresh token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description New token pair */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthTokens"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke a refresh token (18_SECURITY.md) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description Refresh token revoked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search rooms with structured filters + live availability (16_SEARCH_ARCHITECTURE.md) */
        get: {
            parameters: {
                query?: {
                    city?: string;
                    district?: string;
                    roomType?: string;
                    date?: string;
                    startTime?: string;
                    durationMinutes?: number;
                    participants?: number;
                    priceMax?: number;
                    amenities?: string[];
                    sort?: "relevance" | "price" | "distance" | "rating";
                    lat?: number;
                    lng?: number;
                    radiusKm?: number;
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated search results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            results?: components["schemas"]["RoomSummary"][];
                            page?: number;
                            pageSize?: number;
                            totalCount?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spaces/{roomId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full room detail */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    roomId: components["parameters"]["RoomId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Room detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RoomDetail"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spaces/{roomId}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public reviews for a room (APPROVED moderation status only) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    roomId: components["parameters"]["RoomId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reviews list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Review"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spaces/{roomId}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live availability for a room/date (12_RESERVATION_ENGINE.md §12.1) */
        get: {
            parameters: {
                query: {
                    date: string;
                };
                header?: never;
                path: {
                    roomId: components["parameters"]["RoomId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Open windows for the given local calendar date, already filtered to windows that can fit at least the room's own `minBookingMinutes` (BookingsController.getAvailability / AvailabilityService.getOpenWindows — takes only `roomId` and `date`; a previously-documented required `durationMinutes` param was doc-only drift, found and removed while building the room detail page's booking widget — the real endpoint never read it). Each window may be longer than one booking; picking a specific `startAt`/duration within a window, and keeping it within `[minBookingMinutes, maxBookingMinutes]`, is the caller's job. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            slots?: {
                                /** Format: date-time */
                                startAt?: string;
                                /** Format: date-time */
                                endAt?: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a booking hold (DRAFT/PENDING) — 12_RESERVATION_ENGINE.md §12.3 */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description 11_API_CONTRACTS.md §11.2 — required in practice for booking/payment mutations */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        roomId: string;
                        /** Format: date-time */
                        startAt: string;
                        /** Format: date-time */
                        endAt: string;
                        participants?: number;
                        purpose?: string;
                        /** @description Not required in the schema — `CreateBookingDto.customer` is `@IsOptional()`. Only conditionally required, and only at runtime: an unauthenticated (guest) caller must supply `email` or `phone` here, or `BookingsService.create` throws `CUSTOMER_IDENTIFIER_REQUIRED` (400). An authenticated caller's JWT already identifies the customer, so this object is ignored either way once a session exists. Fixed as doc-only drift — a previous version of this doc listed `customer` under the top-level `required` array, which doesn't match `CreateBookingDto`. */
                        customer?: {
                            name?: string;
                            email?: string;
                            phone?: string;
                        };
                    };
                };
            };
            responses: {
                /** @description Booking created (PENDING), price breakdown included */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookingSummary"];
                    };
                };
                /** @description Slot no longer available (race condition — 12_RESERVATION_ENGINE.md §12.2) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{bookingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get booking detail — guest (by opaque id) or the owning authenticated customer
         * @description `@Public()` with an optional bearer token, not a hard auth wall (`BookingsController.getOne`). `POST /bookings` is itself public (guest checkout, 05_USER_FLOWS.md §5.2) and provisions a user account with no JWT issued, so a guest who just booked has no session to prove ownership with — the frontend's payment- confirmation page (`/booking/{bookingId}/confirming`, driven by `payments.successUrlTemplate`) depends on this endpoint working for that guest. Possession of the opaque booking UUID is the gate for an anonymous caller; a caller who *does* send a valid bearer token still gets the ownership check — a non-owning authenticated caller gets 404, never revealing that the booking exists. Fixed as doc-only drift while building the payment-confirmation page: this endpoint previously required auth unconditionally, which would have 401'd every guest booking, the primary case `POST /bookings` supports.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bookingId: components["parameters"]["BookingId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Booking detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookingSummary"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a hosted checkout session (13_PAYMENT_ARCHITECTURE.md §13.3) */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description 11_API_CONTRACTS.md §11.2 — required in practice for booking/payment mutations */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        bookingId: string;
                        /** @enum {string} */
                        provider: "EPOINT" | "PAYRIFF";
                    };
                };
            };
            responses: {
                /** @description Redirect URL to hosted checkout */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uri */
                            checkoutUrl?: string;
                            /** Format: uuid */
                            paymentId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/webhook/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Provider webhook receiver (signature-verified, idempotent — 18_SECURITY.md §18.3) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    provider: "epoint" | "payriff";
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description Acknowledged */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid signature — rejected, no state change */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/refunds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a refund (computed per cancellation policy — 05_USER_FLOWS.md §5.6) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        bookingId: string;
                        reason: string;
                    };
                };
            };
            responses: {
                /** @description Refund requested */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Refund"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List my bookings */
        get: {
            parameters: {
                query?: {
                    status?: "upcoming" | "past" | "cancelled";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Bookings list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookingSummary"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My own profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Profile"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update my own profile (displayName/locale only)
         * @description Deliberately excludes email/phone — those are the OTP-login identifiers, and changing one needs its own re-verification flow (proving continued control of the new value), which isn't built yet. Same allowlist AdminUpdateUserDto already uses for the admin-side equivalent edit.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateProfile"];
                };
            };
            responses: {
                /** @description Updated profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Profile"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/account/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My own payment history — every checkout attempt on my bookings, with its transactions and any refund */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Payment history */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentHistoryEntry"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favorites/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List favorited rooms */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Favorites list. Uses `FavoriteRoomSummary`, not `RoomSummary` — FavoritesService.listForUser()'s raw SQL join (favorite+room+ location+photo) returns a narrower shape (no roomType, verified, capacityMin/Max, lat/lng, available, relevanceScore). A prior version of this doc claimed `RoomSummary[]`; fixed as doc-only drift found while wiring the room detail page's bookmark button. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FavoriteRoomSummary"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favorites/{roomId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether I have favorited this room */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    roomId: components["parameters"]["RoomId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Favorite status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            favorited?: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Favorite a room
         * @description Idempotent — favoriting an already-favorited room just returns the same result.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    roomId: components["parameters"]["RoomId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Added (or already favorited) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            favorited?: true;
                        };
                    };
                };
            };
        };
        /**
         * Unfavorite a room
         * @description Idempotent — unfavoriting a room that isn't favorited just returns the same result.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    roomId: components["parameters"]["RoomId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removed (or already not favorited) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            favorited?: false;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/invoices/{bookingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download booking receipt/invoice — NOT YET IMPLEMENTED, see note above */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bookingId: components["parameters"]["BookingId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Invoice PDF metadata / signed URL */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Invoice"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a review (only for COMPLETED bookings — 18_SECURITY.md §18.6) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        bookingId: string;
                        rating: number;
                        text?: string;
                        photos?: string[];
                    };
                };
            };
            responses: {
                /** @description Review created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Review"];
                    };
                };
                /** @description Booking not eligible for review */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My own submitted reviews, any moderation status
         * @description Unlike GET /spaces/{roomId}/reviews (public, APPROVED-only), this returns every review the caller has submitted regardless of moderation_status — a REJECTED review is still the customer's own content, and they're entitled to see it.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description My reviews */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Review"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register as a provider (self-service — no document verification required) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProviderCreateRequest"];
                };
            };
            responses: {
                /** @description Provider created, verification_status = PENDING */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Provider"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My provider profile (for the caller's PROVIDER_OWNER/PROVIDER_STAFF role) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Provider */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Provider"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List my locations */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Locations */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Location"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a location (requires verification_status != REJECTED — 25_PROVIDER_ARCHITECTURE.md) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LocationInput"];
                };
            };
            responses: {
                /** @description Location created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Location"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/locations/{locationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a location */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    locationId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LocationInput"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/provider/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List bookings across my rooms */
        get: {
            parameters: {
                query?: {
                    locationId?: string;
                    roomId?: string;
                    status?: string;
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Bookings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookingSummary"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a room (subject to plan-tier limits — 25_PROVIDER_ARCHITECTURE.md §25.2) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RoomInput"];
                };
            };
            responses: {
                /** @description Room created (DRAFT) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RoomDetail"];
                    };
                };
                /** @description Plan tier limit reached */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/rooms/{roomId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a room */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    roomId: components["parameters"]["RoomId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RoomInput"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RoomDetail"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/provider/rooms/{roomId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change room status (DRAFT/ACTIVE/INACTIVE) — additive completion (P4-2) of 09_DOMAIN_MODEL.md §9.2's Room lifecycle, which had no API surface in the original contract */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    roomId: components["parameters"]["RoomId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "DRAFT" | "ACTIVE" | "INACTIVE";
                    };
                };
            };
            responses: {
                /** @description Status updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RoomDetail"];
                    };
                };
                /** @description Cannot activate: owning provider is not VERIFIED */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/provider/rooms/{roomId}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a room photo (18_SECURITY.md §18.4 secure upload pipeline) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    roomId: components["parameters"]["RoomId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                    };
                };
            };
            responses: {
                /** @description Photo queued for moderation */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Photo"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/rooms/{roomId}/availability-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set recurring availability rules for a room */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    roomId: components["parameters"]["RoomId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AvailabilityRule"][];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/rooms/{roomId}/blocked-periods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manually block a time range (05_USER_FLOWS.md §5.5) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    roomId: components["parameters"]["RoomId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: date-time */
                        startAt: string;
                        /** Format: date-time */
                        endAt: string;
                        reason?: string;
                    };
                };
            };
            responses: {
                /** @description Blocked period created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BlockedPeriod"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/revenue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Revenue summary (ledger-derived, plan-gated — 21_ANALYTICS.md §21.4) */
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Revenue summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RevenueSummary"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/payouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List my payouts */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Payouts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Payout"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invite a staff member (subject to plan-tier seat limit) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        email: string;
                        /** Format: uuid */
                        locationId?: string;
                        permissionScope: string[];
                    };
                };
            };
            responses: {
                /** @description Staff invited */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/analytics/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Views, search appearances, conversion, occupancy (21_ANALYTICS.md §21.4) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Analytics overview */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProviderAnalyticsOverview"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List providers by verification status */
        get: {
            parameters: {
                query?: {
                    verificationStatus?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Providers */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Provider"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/providers/{providerId}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve/reject provider verification (24_ADMIN_ARCHITECTURE.md §24.2) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    providerId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        decision: "VERIFIED" | "REJECTED";
                        notes?: string;
                    };
                };
            };
            responses: {
                /** @description Verification decision recorded */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search/list all bookings */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Bookings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookingSummary"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List payments */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Payments */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/refunds/{refundId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a refund above the Support/Ops authorized limit (18_SECURITY.md §18.2) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    refundId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Refund approved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/payouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Payout queue (14_PAYOUT_LEDGER.md §14.5), filterable by payee type
         * @description 31_PARTNER_REFERRAL_ARCHITECTURE.md §31.6 — the payeeType filter is additive; omitting it returns both provider and partner payouts as before this addendum.
         */
        get: {
            parameters: {
                query?: {
                    payeeType?: "PROVIDER" | "PARTNER";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Payouts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Payout"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/payouts/{payoutId}/mark-paid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a payout as paid with a bank reference */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    payoutId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        bankReference: string;
                    };
                };
            };
            responses: {
                /** @description Payout marked paid */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/disputes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List disputes (24_ADMIN_ARCHITECTURE.md §24.3) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Disputes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query the audit trail (18_SECURITY.md §18.5) */
        get: {
            parameters: {
                query?: {
                    entityType?: string;
                    entityId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Audit log entries */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditLogEntry"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/r/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Public referral tracking redirect (31_PARTNER_REFERRAL_ARCHITECTURE.md §31.4)
         * @description Looks up the ACTIVE ReferralCampaign by code, records a ReferralClick server-side, sets an httpOnly/Secure/SameSite=Lax cookie carrying only an opaque attribution_token, and redirects. No request/response body — the cookie is the only client-visible artifact, and it proves nothing by itself (the authoritative record is the server-side ReferralClick row).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to the marketplace homepage or landing path; Set-Cookie carries the attribution token */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unknown or inactive campaign code — redirects to the homepage without setting a cookie */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/partners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List/filter partners */
        get: {
            parameters: {
                query?: {
                    status?: "PENDING" | "ACTIVE" | "SUSPENDED";
                    type?: "AFFILIATE" | "AGENCY" | "CORPORATE" | "COMMUNITY" | "STRATEGIC_PARTNER";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Partners */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Partner"][];
                    };
                };
            };
        };
        put?: never;
        /** Create partner (admin-provisioned — no self-signup in V1, §31.7) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PartnerCreateRequest"];
                };
            };
            responses: {
                /** @description Partner created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Partner"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/partners/{partnerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a partner, including status transitions (PENDING/ACTIVE/SUSPENDED) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    partnerId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PartnerUpdateRequest"];
                };
            };
            responses: {
                /** @description Partner updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/admin/partners/{partnerId}/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a partner's referral campaigns */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    partnerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Campaigns */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReferralCampaign"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a referral campaign (trackable code/link) for a partner */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    partnerId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReferralCampaignCreateRequest"];
                };
            };
            responses: {
                /** @description Campaign created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReferralCampaign"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/partners/{partnerId}/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clicks, attributed bookings, commission earned/paid (§31.7 — admin-facing only in V1) */
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                };
                header?: never;
                path: {
                    partnerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Partner analytics summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PartnerAnalytics"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error?: {
                /** @example SLOT_UNAVAILABLE */
                code?: string;
                message?: string;
                details?: Record<string, never>;
            };
        };
        AuthTokens: {
            accessToken: string;
            refreshToken: string;
            /** @description access token lifetime in seconds */
            expiresIn: number;
        };
        Money: {
            /** @description minor units (qəpik) */
            amount?: number;
            /** @example AZN */
            currency?: string;
        };
        RoomSummary: {
            /** Format: uuid */
            id?: string;
            name?: string;
            roomType?: string;
            providerName?: string;
            verified?: boolean;
            city?: string;
            district?: string;
            lat?: number;
            lng?: number;
            distanceKm?: number;
            capacityMin?: number;
            capacityMax?: number;
            pricePerHour?: components["schemas"]["Money"];
            averageRating?: number;
            reviewCount?: number;
            /** Format: uri */
            coverPhotoUrl?: string;
            available?: boolean;
            relevanceScore?: number;
        };
        Profile: {
            /** Format: uuid */
            id?: string;
            email?: string | null;
            phone?: string | null;
            displayName?: string | null;
            /** @example az */
            locale?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        UpdateProfile: {
            displayName?: string;
            /** @enum {string} */
            locale?: "az" | "en" | "ru" | "tr" | "es" | "de";
        };
        FavoriteRoomSummary: {
            /** Format: uuid */
            id?: string;
            name?: string;
            city?: string;
            district?: string;
            pricePerHour?: components["schemas"]["Money"];
            averageRating?: number;
            reviewCount?: number;
            /** Format: uri */
            coverPhotoUrl?: string;
            /** Format: date-time */
            favoritedAt?: string;
        };
        RoomDetail: components["schemas"]["RoomSummary"] & {
            description?: string;
            sizeSqm?: number;
            amenities?: string[];
            cancellationPolicy?: Record<string, never>;
            photos?: string[];
            minBookingMinutes?: number;
            maxBookingMinutes?: number;
        };
        RoomInput: {
            /** Format: uuid */
            locationId: string;
            /** Format: uuid */
            roomTypeId: string;
            name: string;
            description?: string;
            capacityMin?: number;
            capacityMax: number;
            sizeSqm?: number;
            basePriceAmount: number;
            /** @default AZN */
            basePriceCurrency: string;
            amenityIds?: string[];
            cancellationPolicy?: Record<string, never>;
        };
        AvailabilityRule: {
            /** @enum {string} */
            recurrenceType?: "WEEKLY" | "DATE_SPECIFIC";
            dayOfWeek?: number;
            /** Format: date */
            specificDate?: string;
            startTime?: string;
            endTime?: string;
            isOpen?: boolean;
        };
        BlockedPeriod: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            startAt?: string;
            /** Format: date-time */
            endAt?: string;
            reason?: string;
        };
        Photo: {
            /** Format: uuid */
            id?: string;
            /** Format: uri */
            url?: string;
            moderationStatus?: string;
        };
        /** @description Matches the real shape returned by `BookingsService.create` / `findById` / `listForCustomer` — the raw `BookingEntity` plus its `items` relation, not a hand-assembled DTO. Fixed as doc-only drift: a previous version of this schema had a single `room` (a full `RoomSummary`) and top-level `startAt`/`endAt`, and priced `grossAmount`/`serviceFeeAmount`/`totalAmount` as three separate `Money` objects. The entity has neither — pricing is one shared `currency` column plus three plain integer (minor-unit) amount columns, and the room/time range live per line-item on `booking_item` (`items[]`), not on the booking itself; a booking may in principle cover more than one item/room. `booking_item` only stores `roomId`, not a full room summary — the frontend already has the room's display details from the room detail page it booked from. */
        BookingSummary: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            customerUserId?: string;
            /** @enum {string} */
            status?: "DRAFT" | "PENDING" | "PAYMENT_PENDING" | "CONFIRMED" | "COMPLETED" | "CANCELLED" | "EXPIRED" | "NO_SHOW" | "REFUND_PENDING" | "REFUNDED";
            /** @enum {string} */
            mode?: "REQUEST_BASED" | "PAYMENT_BASED";
            /** @example AZN */
            currency?: string;
            /** @description minor units (qəpik) */
            grossAmount?: number;
            /** @description minor units (qəpik) */
            serviceFeeAmount?: number;
            /** @description minor units (qəpik) */
            totalAmount?: number;
            purpose?: string | null;
            participantsCount?: number | null;
            /** Format: date-time */
            holdExpiresAt?: string | null;
            /** Format: date-time */
            createdAt?: string;
            items?: {
                /** Format: uuid */
                id?: string;
                /** Format: uuid */
                roomId?: string;
                /** Format: date-time */
                startAt?: string;
                /** Format: date-time */
                endAt?: string;
                /** @description minor units (qəpik) */
                unitPriceAmount?: number;
                quantity?: number;
                /** @enum {string} */
                status?: "DRAFT" | "PENDING" | "PAYMENT_PENDING" | "CONFIRMED" | "COMPLETED" | "CANCELLED" | "EXPIRED" | "NO_SHOW" | "REFUND_PENDING" | "REFUNDED";
            }[];
        };
        Refund: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            bookingId?: string;
            amount?: components["schemas"]["Money"];
            /** @enum {string} */
            status?: "REQUESTED" | "APPROVED" | "PROCESSING" | "COMPLETED" | "REJECTED";
        };
        Invoice: {
            /** Format: uuid */
            id?: string;
            invoiceNumber?: string;
            amount?: components["schemas"]["Money"];
            /** Format: uri */
            pdfUrl?: string;
        };
        PaymentHistoryEntry: {
            /**
             * Format: uuid
             * @description payment id (one per checkout attempt)
             */
            id?: string;
            /** Format: uuid */
            bookingId?: string;
            /** @enum {string} */
            providerAdapter?: "EPOINT" | "PAYRIFF" | "STRIPE";
            /** @enum {string} */
            status?: "INITIATED" | "AUTHORIZED" | "CAPTURED" | "FAILED" | "CANCELLED" | "REFUND_PENDING" | "PARTIALLY_REFUNDED" | "REFUNDED" | "CHARGEBACK";
            /** @description minor units (qəpik) */
            bookingTotalAmount?: number;
            /** @example AZN */
            bookingCurrency?: string;
            /** @enum {string} */
            bookingStatus?: "DRAFT" | "PENDING" | "PAYMENT_PENDING" | "CONFIRMED" | "COMPLETED" | "CANCELLED" | "EXPIRED" | "NO_SHOW" | "REFUND_PENDING" | "REFUNDED";
            /**
             * Format: uuid
             * @description the booking's first booking_item.room_id
             */
            roomId?: string | null;
            /** Format: date-time */
            createdAt?: string;
            transactions?: {
                /** Format: uuid */
                id?: string;
                /** @enum {string} */
                type?: "CHARGE" | "REFUND";
                /** @description minor units (qəpik) */
                amount?: number;
                /** @example AZN */
                currency?: string;
                /** @enum {string} */
                status?: "INITIATED" | "AUTHORIZED" | "CAPTURED" | "FAILED" | "CANCELLED";
                /** Format: date-time */
                createdAt?: string;
            }[];
            refunds?: {
                /** Format: uuid */
                id?: string;
                /** @description minor units (qəpik) */
                amount?: number;
                /** @example AZN */
                currency?: string;
                /** @enum {string} */
                status?: "REQUESTED" | "APPROVED" | "PROCESSING" | "COMPLETED" | "REJECTED";
                reason?: string | null;
                /** Format: date-time */
                createdAt?: string;
            }[];
        };
        Review: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            bookingId?: string;
            /** Format: uuid */
            customerUserId?: string;
            /** Format: uuid */
            roomId?: string;
            rating?: number;
            text?: string | null;
            photos?: string[] | null;
            providerReplyText?: string | null;
            /** Format: date-time */
            providerReplyAt?: string | null;
            /** @enum {string} */
            moderationStatus?: "PENDING" | "APPROVED" | "REJECTED";
            /** Format: date-time */
            createdAt?: string;
        };
        Provider: {
            /** Format: uuid */
            id?: string;
            legalName?: string;
            displayName?: string;
            slug?: string;
            category?: string | null;
            /** @enum {string} */
            verificationStatus?: "PENDING" | "VERIFIED" | "REJECTED" | "SUSPENDED";
            /** @enum {string} */
            planTier?: "FREE" | "STARTER" | "PRO" | "ENTERPRISE";
            commissionPercentage?: number | null;
        };
        ProviderCreateRequest: {
            legalName: string;
            displayName: string;
            category?: string;
        };
        Location: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            providerId?: string;
            name?: string;
            addressLine?: string;
            city?: string;
            district?: string | null;
            /** @example AZ */
            countryCode?: string;
            lat?: number;
            lng?: number;
            /** @example Asia/Baku */
            timezone?: string;
            openingHours?: Record<string, never> | null;
        };
        LocationInput: {
            name: string;
            addressLine: string;
            city: string;
            district?: string;
            /** @default AZ */
            countryCode: string;
            lat: number;
            lng: number;
            /** @default Asia/Baku */
            timezone: string;
            openingHours?: Record<string, never>;
        };
        RevenueSummary: {
            grossTotal?: components["schemas"]["Money"];
            platformFeeTotal?: components["schemas"]["Money"];
            netTotal?: components["schemas"]["Money"];
            bookingCount?: number;
        };
        Payout: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            periodStart?: string;
            /** Format: date-time */
            periodEnd?: string;
            amount?: components["schemas"]["Money"];
            /** @enum {string} */
            status?: "PENDING" | "AVAILABLE" | "PROCESSING" | "PAID" | "FAILED" | "REVERSED";
        };
        ProviderAnalyticsOverview: {
            views?: number;
            searchAppearances?: number;
            bookingConversionRate?: number;
            occupancyRate?: number;
        };
        AuditLogEntry: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            actorUserId?: string;
            action?: string;
            entityType?: string;
            /** Format: uuid */
            entityId?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        Partner: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** @enum {string} */
            type?: "AFFILIATE" | "AGENCY" | "CORPORATE" | "COMMUNITY" | "STRATEGIC_PARTNER";
            /** @enum {string} */
            status?: "PENDING" | "ACTIVE" | "SUSPENDED";
            /** Format: email */
            contactEmail?: string | null;
            contactPhone?: string | null;
            /** @enum {string} */
            defaultCommissionType?: "PERCENTAGE_OF_PLATFORM_FEE" | "FIXED_PER_BOOKING";
            /** @description Minor units if FIXED_PER_BOOKING, basis points if PERCENTAGE_OF_PLATFORM_FEE */
            defaultCommissionValue?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        PartnerCreateRequest: {
            name: string;
            /** @enum {string} */
            type: "AFFILIATE" | "AGENCY" | "CORPORATE" | "COMMUNITY" | "STRATEGIC_PARTNER";
            /** Format: email */
            contactEmail?: string;
            contactPhone?: string;
            /** @enum {string} */
            defaultCommissionType: "PERCENTAGE_OF_PLATFORM_FEE" | "FIXED_PER_BOOKING";
            defaultCommissionValue: number;
        };
        PartnerUpdateRequest: {
            name?: string;
            /** @enum {string} */
            status?: "PENDING" | "ACTIVE" | "SUSPENDED";
            /** Format: email */
            contactEmail?: string;
            contactPhone?: string;
            /** @enum {string} */
            defaultCommissionType?: "PERCENTAGE_OF_PLATFORM_FEE" | "FIXED_PER_BOOKING";
            defaultCommissionValue?: number;
        };
        ReferralCampaign: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            partnerId?: string;
            name?: string;
            /** @example BLOGGER123 */
            code?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "PAUSED" | "ENDED";
            /** @example 30 */
            attributionWindowDays?: number;
            /** @enum {string|null} */
            commissionTypeOverride?: "PERCENTAGE_OF_PLATFORM_FEE" | "FIXED_PER_BOOKING" | null;
            commissionValueOverride?: number | null;
            /** Format: date-time */
            startsAt?: string | null;
            /** Format: date-time */
            endsAt?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        ReferralCampaignCreateRequest: {
            name: string;
            /** @description Unique, human-facing (e.g. a blogger's handle) */
            code: string;
            /** @default 30 */
            attributionWindowDays: number;
            /** @enum {string} */
            commissionTypeOverride?: "PERCENTAGE_OF_PLATFORM_FEE" | "FIXED_PER_BOOKING";
            commissionValueOverride?: number;
            /** Format: date-time */
            startsAt?: string;
            /** Format: date-time */
            endsAt?: string;
        };
        PartnerAnalytics: {
            /** Format: uuid */
            partnerId?: string;
            totalClicks?: number;
            attributedBookings?: number;
            commissionEarned?: components["schemas"]["Money"];
            commissionPaid?: components["schemas"]["Money"];
            commissionPending?: components["schemas"]["Money"];
            byCampaign?: {
                /** Format: uuid */
                campaignId?: string;
                code?: string;
                clicks?: number;
                attributedBookings?: number;
                commissionEarned?: components["schemas"]["Money"];
            }[];
        };
    };
    responses: {
        /** @description Not authenticated */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found (or not owned by caller — 11_API_CONTRACTS.md §11.4) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many requests */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        RoomId: string;
        BookingId: string;
        /** @description 11_API_CONTRACTS.md §11.2 — required in practice for booking/payment mutations */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
